---
# tasks file for instance.ssh_aws_public_key
- name: Add SSH public key to AWS System Log.
  lineinfile:
    dest: /etc/rc.local
    insertbefore: 'exit 0'
    line: '/usr/bin/ssh-keygen -y -f /etc/ssh/ssh_host_ecdsa_key'
