---
# stuffs-example-instance.yml
# an example instance created for the stuffs inventory scraper.
# ansible-playbook stuffs-example-instance.yml -i inventory/stuffs_demo -e "env=stuffs-demo instances=example_private region=us-east-1"
- hosts: localhost
  connection: local
  gather_facts: yes
  vars_files:
    - vars/stuffs.yml
  roles:
    - role: aws.ec2_facts
      filters:
        "tag:Environment": "{{ env }}"
        instance-state-name: running
    - role: localhost.aws_ssh_keys
    - role: ansible.groups_init

# Python configuration
- hosts: web1_private:db1_private
  become: yes
  gather_facts: no
  user: ubuntu
  roles:
    - role: ubuntu.raw_install_python
    - role: instance.ssh_aws_public_key # dumps the SSH public key to AWS System Log
