---
# stuffs.yml
# this Ansible playbook gathers all instances in a region and inventories them.
- hosts: localhost
  connection: local
  gather_facts: yes
  vars_files:
    - vars/stuffs.yml
  roles:
    - role: aws.ec2_facts
      filters:
        "tag:Environment": "{{ env }}"
        instance-state-name: running
    - role: localhost.aws_ssh_keys
    - role: ansible.groups_init

- hosts: instances_private
  become: yes
  gather_facts: yes
  user: ubuntu
  vars_files:
    - vars/stuffs.yml
  roles:
    - role: instance.get_inventory

- hosts: localhost
  connection: local
  gather_facts: yes
  vars_files:
    - vars/stuffs.yml
  roles:
    - role: localhost.generate_hugo_and_upload
