---
# vpc_create.yml
#
# This playbook deploys an AWS infrastructure, including VPC, subnets, and routes.
#
#####
# Initial AWS deployment
#####
- hosts: localhost
  connection: local
  gather_facts: yes

  vars_files:
    - "vars/{{ env }}_aws/aws.yml"
    - "vars/{{ env }}_aws/vault.yml"

  roles:
    - role: aws.vpc
    - role: aws.vpc_facts
      filters:
        "tag:Environment": "{{ env }}"
    - role: aws.routes
