---
# tasks file for localhost.ssh_init
- name: Touch .ssh/config file.
  file:
    path: "{{ ansible_env.HOME }}/.ssh/config"
    state: touch

# Couldn't get blockinfile with state = absent to work. Used multi-line sed instead.
- name: Remove all key references from SSH files.
  shell: "sed -i.ansible_backup '/^# {{ nat_vars.instance_tags.Organization }}/,/^# {{ nat_vars.instance_tags.Organization }}/d' {{ ansible_env.HOME }}/.ssh/config"

- name: Set CIDR subnet fact.
  set_fact:
    nat_CIDR_fact: "{{ subnet_facts.subnets|selectattr('tags.Name', 'equalto', nat_vars.subnet)|map(attribute='cidr_block')|list|first }}"

# NOTE.  IF YOU USE VIRGINIA, IT WILL BE EC2.INTERNAL, NOT COMPUTE.INTERNAL
- name: Configure SSH proxy host.
  blockinfile:
    dest: "{{ ansible_env.HOME }}/.ssh/config"
    marker: "# {{ nat_vars.instance_tags.Organization }}"
    block: |
      Host ip-{{ nat_CIDR_fact.split('.')[0]}}-{{ nat_CIDR_fact.split('.')[1]}}-*-*.compute.internal
           ProxyCommand ssh -i ~/.ssh/{{ vault_vars.key_pair }} -W %h:%p -q centos@{{ nat_public_dns_facts_vars }}
           ServerAliveInterval 30

- name: Remove all old known_hosts entries.
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.ssh/known_hosts"
    regexp: "^.* # {{ nat_vars.instance_tags.Organization }}"
    state: absent

- name: Import nat SSH fingerprint.
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.ssh/known_hosts"
    line: "{{ nat_public_dns_facts_vars }},{{ nat_public_ip_facts_vars }} {{ ssh_knownhosts_vars.buildami_base }} # {{ nat_vars.instance_tags.Organization }}"
    insertafter: 'EOF'

# - name: Import SSH fingerprints for other hosts.
#   lineinfile:
#     dest: "{{ ansible_env.HOME }}/.ssh/known_hosts"
#     line: "{{ item }} {{ ssh_knownhosts_vars.buildami_base }} # {{ nat_vars.instance_tags.Organization }}"
#   with_items: ec2_facts_vars.instances|selectattr('state', 'equalto', 'running')|map(attribute='private_dns_name')|list
