---
# tasks file for aws.securitygroups
- name: Set fact - NAT SSH rules.
  set_fact:
    nat_ssh_rules:
      - proto: tcp
        from_port: '22'
        to_port: '22'
        cidr_ip: "{{ nat_ip_facts_vars }}/32"

- name: Create inbound rules.
  ec2_group:
    aws_secret_key: "{{ vault_vars.aws_secret_key }}"
    aws_access_key: "{{ vault_vars.aws_access_key }}"
    region: "{{ vault_vars.region }}"
    description: "{{ item.Name }} inbound rules"
    name: "{{ item.Name }}"
    rules: "{{ item.rules | union(nat_ssh_rules)}}"
    vpc_id: "{{ subnet_facts_vars.subnets|selectattr('tags.Name', 'equalto', nat_vars.subnet)|map(attribute='vpc_id')|list|first }}"
  register: securitygroups_facts
  with_items: securitygroups_vars

- name: Tag inbound traffic rules.
  ec2_tag:
    aws_secret_key: "{{ vault_vars.aws_secret_key }}"
    aws_access_key: "{{ vault_vars.aws_access_key }}"
    region: "{{ vault_vars.region }}"
    resource: "{{ item.0.group_id }}"
    state: present
    tags:
      Name: "{{ item.1.Name }}"
      Environment: "{{ item.1.Environment }}"
      Organization: "{{ item.1.Organization }}"
  with_together:
    - "{{ securitygroups_facts.results }}"
    - "{{ securitygroups_vars }}"
