---
# tasks file for localhost.ssh_key_configure
- name: Ensure .ssh directory exists.
  file:
    dest: "{{ vault.ansible_ssh_key_file | dirname }}"
    mode: 0700
    owner: "{{ ansible_ssh_user }}"
    state: directory

- name: Install ssh key
  copy:
    content: "{{ vault.ansible_ssh_key_contents }}"
    dest: "{{ vault.ansible_ssh_key_file }}"
    mode: 0600
    owner: "{{ ansible_ssh_user }}"
