---
# tasks file for nat.config
- name: Upgrade all packages.
  yum:
    name: '*'
    state: latest
    update_cache: yes

- name: Install iptables-service.
  yum:
    name: iptables-services
    state: latest

- name: Enable ip forwarding.
  sysctl:
    name: "{{ nat_vars.host_settings.ipv4_ip_forward }}"
    value: 1
    ignoreerrors: yes

# Hack to set CIDR to /16.  Modify as you need.
- name: Set VPC CIDR.
  set_fact:
    vpc_CIDR_fact: "{{ nat_CIDR_fact_vars.split('/')[0] }}/16"

- name: Upload iptables template.
  template:
    src: files/templates/iptables-nat.j2
    dest: "/etc/sysconfig/iptables"
    owner: "root"
    group: "root"
    mode: "0600"
  with_items: vpc_CIDR_fact

- name: Reload iptables.
  service:
    name: iptables
    state: restarted
