---
# tasks file for instance.controller
- name: Get ec2_facts.
  ec2_facts:
  register: ec2_facts

- name: Set domain suffix.
  set_fact:
    domain_suffix: "{{ ec2_facts.ansible_facts.ansible_ec2_placement_region }}"

- name: Set AWS hostname
  set_fact:
    aws_hostname: "{{ ec2_facts.ansible_facts.ansible_ec2_hostname }}"

- name: Create the {{ volume_path }} directory.
  file:
    path: "{{ volume_path }}/controller/{{ item }}"
    state: directory
  with_items:
    - ssl

- name: Symlink /var/lib/kubernetes.
  file:
    src: "{{ volume_path }}/controller"
    dest: /var/lib/kubernetes
    state: link

- name: Copy in CFSSL certificates.
  copy:
    src: "./ssl/{{ env }}/{{ item }}"
    dest: "{{ volume_path }}/controller/ssl/{{ item }}"
  with_items:
    - controller-ca.pem
    - controller-key.pem
    - controller.pem
    - etcdclient-ca.pem
    - etcdclient-key.pem
    - etcdclient.pem
    - node-ca.pem
  notify:
    - restart_kube_apiserver
    - restart_kube_controller_manager

- name: Create a SSL cert and CA PEM file.
  shell: cat {{ volume_path }}/controller/ssl/controller.pem {{ volume_path }}/controller/ssl/controller-ca.pem > {{ volume_path }}/controller/ssl/controller-cert-ca.pem

- name: Download Kubernetes.
  get_url:
    url: "https://dl.k8s.io/{{ kubernetes_version }}/kubernetes-server-linux-amd64.tar.gz"
    dest: "/opt/{{ kubernetes_version }}-kubernetes-server-linux-amd64.tar.gz"

- name: Untar the Kubernetes file.
  unarchive:
    copy: no
    src: "/opt/{{ kubernetes_version }}-kubernetes-server-linux-amd64.tar.gz"
    dest: /opt/

- name: Copy Kubernetes binaries to /usr/sbin.
  copy:
    remote_src: true
    src: "/opt/kubernetes/server/bin/{{ item }}"
    dest: "/usr/sbin/{{ item }}"
    mode: 0700
  with_items:
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler
    - kubectl

# NOTE THIS SHOULD BE CHANGED.  USE ANSIBLE-VAULT TO STORE THESE CREDENTIALS.
# the config in defaults/main.yml should not be used.
- name: Copy token.csv (make sure the values in defaults/main.yml are overridden).
  copy:
    content: "{{ token_csv }}"
    dest: "{{ volume_path }}/controller/token.csv"
  notify:
    - restart_kube_apiserver

- name: Copy the authorization file.
  copy:
    src: authorization-policy.jsonl
    dest: "{{ volume_path }}/controller/authorization-policy.jsonl"

- name: Disable Kubernetes AWS security group modifications.
  template:
    src: aws.conf.j2
    dest: "{{ volume_path }}/controller/aws.conf"

- name: Template controller systemd files.
  template:
    src: "{{ item }}.j2"
    dest: "/etc/systemd/system/{{ item }}"
  with_items:
    - kube-apiserver.service
    - kube-controller-manager.service
    - kube-scheduler.service
  notify:
    - restart_kube_apiserver
    - restart_kube_controller_manager
    - restart_kube_scheduler

- name: systemctl daemon-reload.
  command: systemctl daemon-reload

- name: Create kubectl config.
  shell: >
    /usr/sbin/kubectl config set-cluster {{ env }} \
      --certificate-authority={{ volume_path }}/controller/ssl/controller-ca.pem \
      --embed-certs=true \
      --server=https://{{ ansible_eth0.ipv4.address }}:6443

- name: Get kubectl credentials.
  shell: cat {{ volume_path }}/controller/token.csv \
           | grep admin \
           | awk -F"," '{ print $1 }'
  register: kubectl_token

- name: Configure kubectl credentials.
  shell: >
    /usr/sbin/kubectl config set-credentials admin \
      --token {{ kubectl_token.stdout }}

- name: Set kubectl context.
  shell: >
    kubectl config set-context default-context \
      --cluster={{ env }} \
      --user=admin

- name: Use the context.
  shell: >
    /usr/sbin/kubectl config use-context default-context \
      --cluster={{ env }} \
      --user=admin
