---
# vars/kubernetes.yml

# Kubernetes internal cluster DNS
cluster_domain: cluster.local
# Kubernetes cluster ID (matches Terraform tag 'KubernetesCluster')
cluster_name: kubes 

# Docker version
docker_version: 1.12.6

# etcd Docker version
etcd_docker_image: quay.io/coreos/etcd:v3.0.17

# Kubernetes CNI version
kubernetes_cni_version: v0.4.0

# Kubernetes version
kubernetes_version: v1.5.2

# adds the current public IP address to the AWS security group for remote access
public_ip: true

# Kubernetes service cluster DNS and IP cidr
service_cluster_dns: 10.254.254.10
service_cluster_ip_range: 10.254.254.0/24

# Configures the local SSH config file to use OpenVPN as an SSH proxy (no VPN required for Ansible configuration)
ssh_proxy: true

# EBS volume mount path.
volume_path: /data

# AWS settings
vpc:
  region: "{{ region | default('us-east-1') }}"
  resource_tags:
    Environment: "{{ env }}"
