---
# Wordpress and mysql instances.
# docker settings
openvpn_docker_image: bcawthra/openvpn-openvpn:20161023190213
# AWS instance settings. Note that they are list of dictionaries.
ec2:
  - assign_public_ip: no
    assign_elastic: "{{ vault.elastic }}"
    count_tag:
      Name: openvpn
    exact_count: 1
    groups:
      - openvpn_inbound
    instance_profile_name: openvpn_role
    instance_tags:
      Name: openvpn
      Environment: "{{ env }}"
      Role: vpn
    instance_type: t2.nano
    keypair: "{{ env }}"
    subnet: public
    wait: yes
# iam role
iam:
  - iam_type: role
    name: openvpn_role
    state: present
# security groups
securitygroups:
  - name: openvpn_inbound
    description: 'openvpn inbound rules'
    rules:
      - proto: udp
        from_port: 1194
        to_port: 1194
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: "{{ vault.ip_address }}/32"
    tags:
      Name: "openvpn_inbound"
      Environment: "{{ env }}"
