---
# tasks file for aws.securitygroups
- name: Get current public IP address.
  ipify_facts:
  when: public_ip == 'true'

- name: Set fact - create current public IP address SSH rules.
  set_fact:
    current_public_ip_rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: "{{ ipify_public_ip }}/32"
  when: public_ip == 'true'

- name: Set fact - bastionhost SSH rules (if defined).
  set_fact:
    bastionhost_ssh_rules:
      - proto: tcp
        from_port: '22'
        to_port: '22'
        cidr_ip: "{{ bastionhost_instance_results.tagged_instances.0.private_ip }}/32"
  when: bastionhost_instance_results is defined

- name: Create security groups.
  ec2_group:
    region: "{{ vpc.region }}"
    description: "{{item.description }}"
    name: "{{ item.name }}"
    rules: "{{ item.rules | union(bastionhost_ssh_rules) | union(current_public_ip_rules) }}"
    vpc_id: "{{ vpc_id_fact }}"
  register: securitygroups_results
  with_items: "{{ securitygroups }}"

- name: Tag inbound traffic rules.
  ec2_tag:
    region: "{{ vpc.region }}"
    resource: "{{ item.0.group_id }}"
    state: present
    tags: "{{ item.1.tags }}"
  with_together:
    - "{{ securitygroups_results.results }}"
    - "{{ securitygroups }}"
