---
# tasks file for aws.securitygroups
- name: Set fact - bastionhost SSH rules (if defined).
  set_fact:
    bastionhost_ssh_rules:
      - proto: tcp
        from_port: '22'
        to_port: '22'
        cidr_ip: "{{ bastionhost_instance_results.tagged_instances.0.private_ip }}/32"
  when: bastionhost_instance_results is defined

- name: Create security groups.
  ec2_group:
    aws_secret_key: "{{ vault.aws_secret_key }}"
    aws_access_key: "{{ vault.aws_access_key }}"
    region: "{{ vpc.region }}"
    description: "{{item.description }}"
    name: "{{ item.name }}"
    rules: "{{ item.rules | union(bastionhost_ssh_rules) }}"
    vpc_id: "{{ vpc_id_fact }}"
  register: securitygroups_results
  with_items: "{{ securitygroups }}"

- name: Tag inbound traffic rules.
  ec2_tag:
    aws_secret_key: "{{ vault.aws_secret_key }}"
    aws_access_key: "{{ vault.aws_access_key }}"
    region: "{{ vpc.region }}"
    resource: "{{ item.0.group_id }}"
    state: present
    tags: "{{ item.1.tags }}"
  with_together:
    - "{{ securitygroups_results.results }}"
    - "{{ securitygroups }}"
