---
# tasks file for aws.routes
# NOTE - as of 02/29/2016 this requires a patch -
# https://github.com/bonovoxly/ansible-modules-extras/blob/fix_1510_route_tables_remove_routes_blackhole/cloud/amazon/ec2_vpc_route_table.py
# See './library/ec2_vpc_route_table.py'
- name: Ensure that the VPC has an Internet Gateway.
  ec2_vpc_igw:
    aws_secret_key: "{{ vault_vars.aws_secret_key }}"
    aws_access_key: "{{ vault_vars.aws_access_key }}"
    region: "{{ vault_vars.region }}"
    state: present
    vpc_id: "{{ subnet_facts_vars.subnets|selectattr('tags.Name', 'equalto', nat_vars.subnet)|map(attribute='vpc_id')|list|first }}"
  register: igw_facts
  tags:
    - AWS
    - Network
    - Routing

- name: Get private routing table.
  ec2_vpc_route_table_facts:
    aws_secret_key: "{{ vault_vars.aws_secret_key }}"
    aws_access_key: "{{ vault_vars.aws_access_key }}"
    region: "{{ vault_vars.region }}"
    filters:
      "tag:Name": "{{ aws_vpc_vars.private_route.resource_tags.Name }}"

- name: Get public routing table.
  ec2_vpc_route_table_facts:
    aws_secret_key: "{{ vault_vars.aws_secret_key }}"
    aws_access_key: "{{ vault_vars.aws_access_key }}"
    region: "{{ vault_vars.region }}"
    filters:
      "tag:Name": "{{ aws_vpc_vars.public_route.resource_tags.Name }}"

- name: Create private route.
  ec2_vpc_route_table:
    aws_secret_key: "{{ vault_vars.aws_secret_key }}"
    aws_access_key: "{{ vault_vars.aws_access_key }}"
    region: "{{ vault_vars.region }}"
    state: present
    subnets: "{{ subnet_facts_vars.subnets|selectattr('tags.Route', 'equalto', 'private')|map(attribute='cidr_block')|join(',') }}"
    routes:
      - dest: "{{ aws_vpc_vars.private_route.routes.dest }}"
        instance_id: "{{ nat_id_facts_vars }}"
    tags: "{{ aws_vpc_vars.private_route.resource_tags }}"
    vpc_id: "{{ subnet_facts_vars.subnets|selectattr('tags.Name', 'equalto', nat_vars.subnet)|map(attribute='vpc_id')|list|first }}"

- name: Create public route.
  ec2_vpc_route_table:
    aws_secret_key: "{{ vault_vars.aws_secret_key }}"
    aws_access_key: "{{ vault_vars.aws_access_key }}"
    region: "{{ vault_vars.region }}"
    state: present
    subnets: "{{ subnet_facts_vars.subnets|selectattr('tags.Route', 'equalto', 'public')|map(attribute='cidr_block')|join(',') }}"
    routes:
      - dest: "{{ aws_vpc_vars.public_route.routes.dest }}"
        gateway_id: "{{ igw_facts.gateway_id }}"
    tags: "{{aws_vpc_vars.public_route.resource_tags }}"
    vpc_id: "{{ subnet_facts_vars.subnets|selectattr('tags.Name', 'equalto', nat_vars.subnet)|map(attribute='vpc_id')|list|first }}"
