---
# AWS settings for mod_aws
# cidr value (can be overridden via -e)
cidr: '10.231'
# Route53 settings
route53:
  domain: ec2.internal
# VPC settings
vpc:
  cidr_block: "{{ cidr }}.0.0/16"
  gateway: yes
  image: ami-fd6e3bea
  image_user: ubuntu
  keypair: "{{ keypair | default('mod') }}"
  region: us-east-1
  resource_tags:
    Name: "mod_vpc"
    Environment: mod
  subnets:
    - cidr: "{{ cidr }}.0.0/24"
      az: us-east-1b
      resource_tags:
        Name: public
        Environment: mod
        Role: public_subnet
        Route: public
  public_route:
    routes:
      dest: 0.0.0.0/0
    resource_tags:
      Name: public_route
      Environment: mod
