---
# tasks file for aws.facts
- name: Gather EC2 facts.
  ec2_remote_facts:
    aws_secret_key: "{{ vault_vars.aws_secret_key }}"
    aws_access_key: "{{ vault_vars.aws_access_key }}"
    region: "{{ vault_vars.region }}"
    filters:
      "tag:Environment": aws
  register: ec2_facts
