---
# tasks file for instances.config
- name: Upgrade all packages.
  yum:
    name: '*'
    state: latest
    update_cache: yes

- name: Install EPEL.
  yum:
    name: epel-release
    state: latest

- name: Install iptables-service.
  yum:
    name: iptables-services
    state: latest

- name: Upload iptables template.
  template:
    src: files/templates/iptables.j2
    dest: "/etc/sysconfig/iptables"
    owner: "root"
    group: "root"
    mode: "0600"

- name: Install Docker repo.
  copy:
    src: "files/docker.repo"
    dest: "/etc/yum.repos.d/docker.repo"
    owner: root
    group: root
    mode: '0644'

- name: Install GPG key.
  get_url:
    url: "https://yum.dockerproject.org/gpg"
    dest: "/etc/pki/rpm-gpg/"
    owner: root
    group: root
    mode: '0644'

- name: Install Docker.
  yum:
    name: docker-engine
    state: present
  register: install_docker_results

- name: Install docker-py.
  yum:
    name: python-docker-py
    state: latest

- name: Restart and enable Docker.
  service:
    name: docker
    enabled: yes
    state: started
  when: install_docker_results.changed
