---
# tasks file for bastionhost.nat_config
- name: Install iptables and iptables-persistent.
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - iptables
    - iptables-persistent

- name: Enable ip forwarding.
  sysctl:
    name: net.ipv4.ip_forward
    value: 1

- name: Configure iptables.
  template:
    src: iptables-nat.j2
    dest: /etc/iptables/rules.v4
    owner: root
    group: root
    mode: '0600'

- name: Reload iptables.
  shell: iptables-restore < /etc/iptables/rules.v4
