---
# AWS VPC
aws_vpc:
  name: aws
  cidr_block: '10.148.0.0/16'
  gateway: yes
  region: 'us-west-2'
  state: present
  resource_tags:
    Name: "aws-VPC"
    Organization: b_dev
    Environment: aws
  subnets:
    - cidr: "10.148.0.0/24"
      az: "us-west-2a"
      resource_tags:
        Name: "aws-dmz"
        Organization: b_dev
        Environment: aws
        Role: dmz
        Route: public
    - cidr: "10.148.1.0/24"
      az: "us-west-2a"
      resource_tags:
        Name: "aws-internal"
        Organization: b_dev
        Environment: aws
        Role: internal
        Route: private
    - cidr: "10.148.2.0/24"
      az: "us-west-2a"
      resource_tags:
        Name: "aws-rancher"
        Organization: b_dev
        Environment: aws
        Role: rancher
        Route: private
  private_route:
    routes:
      dest: 0.0.0.0/0
    resource_tags:
        Name: "aws-internal_route"
        Organization: b_dev
        Environment: aws
  public_route:
    routes:
      dest: 0.0.0.0/0
    resource_tags:
      Name: "aws-external_route"
      Organization: b_dev
      Environment: aws
