# deploy script to test ec2_vpc_route_table bug
---
#####
# Initial AWS deployment
#####
- hosts: localhost
  connection: local
  gather_facts: yes

  pre_tasks:
    - name: Ensure .ssh directory exists.
      file:
        dest: "{{ vault.ansible_ssh_key_file | dirname }}"
        mode: 0700
        owner: "{{ ansible_ssh_user }}"
        state: directory

    - name: Install ssh key
      copy:
        content: "{{ vault.ansible_ssh_key_contents }}"
        dest: "{{ vault.ansible_ssh_key_file }}"
        mode: 0600
        owner: "{{ ansible_ssh_user }}"
  roles:
    # Create VPC
    - role: aws.vpc
      vault_vars: "{{ hostvars['127.0.0.1']['vault'] }}"
      vpc_vars: "{{ hostvars['127.0.0.1']['aws_vpc'] }}"
    # Create IAM roles and policies
    - role: aws.iam
      iam_role_vars: "{{ hostvars['127.0.0.1']['la_roles'] }}"
      vault_vars: "{{ hostvars['127.0.0.1']['vault'] }}"
      vpc_vars: "{{ hostvars['127.0.0.1']['aws_vpc'] }}"
    # Create NAT instance
    - role: aws.instances.nat
      nat_vars: "{{ hostvars['127.0.0.1']['natinstance'] }}"
      vault_vars: "{{ hostvars['127.0.0.1']['vault'] }}"
      vpc_vars: "{{ hostvars['127.0.0.1']['aws_vpc'] }}"
    # Create routes
    - role: aws.routes
      vault_vars: "{{ hostvars['127.0.0.1']['vault'] }}"
      vpc_vars: "{{ hostvars['127.0.0.1']['aws_vpc'] }}"
