---
# tasks file for aws.vpc
- name: Create VPC.
  ec2_vpc:
    region: "{{ vpc.region }}"
    state: present
    cidr_block: "{{ vpc.cidr_block }}"
    internet_gateway: "{{ vpc.gateway }}"
    resource_tags: "{{ vpc.resource_tags }}"
    subnets: "{{ vpc.subnets }}"
  register: vpc_register
