---
# tasks file for instance.docker_install
# https://docs.docker.com/engine/installation/linux/ubuntulinux/
- name: Install Docker apt key.
  apt_key:
    keyserver: "{{ docker_keyserver }}"
    id: "{{ docker_id }}"

- name: Create the apt sources file.
  copy:
    src: docker.list
    dest: /etc/apt/sources.list.d/docker.list

- name: Update apt cache.
  apt:
    update_cache: yes

- name: Install Docker.
  apt:
    name: "docker-engine"
    state: present

- name: Create systemd Docker service directory.
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    mode: 0755

- name: Configure Docker storage.
  template:
    src: storage.conf.j2
    dest: /etc/systemd/system/docker.service.d/storage.conf
    mode: 0644
  notify:
    - restart_docker

- name: Reload Systemd.
  command: systemctl daemon-reload

- name: Always notify Docker starter handler.
  debug:
    msg: "Trigger start_docker handler."
  changed_when: true
  notify:
    - start_docker
