---
# tasks file for aws.iam
- name: Create IAM roles.
  iam:
    region: "{{ vpc.region }}"
    name: "{{ item.name }}"
    iam_type: "{{ item.iam_type }}"
    state: "{{ item.state }}"
  register: iam_results
  with_items: "{{ iam }}"

- name: Pause when new IAM roles are created.
  pause:
    seconds: 7
  when: iam_results.changed
