---
# tasks file for localhost.bastion_ssh_config
- name: Touch .ssh/config file.
  file:
    path: "{{ ansible_env.HOME }}/.ssh/config"
    state: touch

# Couldn't get blockinfile with state = absent to work. Used multi-line sed instead.
- name: Remove previous SSH config settings for this organization.
  shell: "sed -i.ansible_backup '/^# {{ marker_vars|default(vpc.resource_tags.Organization) }}/,/^# {{ marker_vars|default(vpc.resource_tags.Organization) }}/d' {{ ansible_env.HOME }}/.ssh/config"

# NOTE.  IF YOU USE VIRGINIA, IT WILL BE EC2.INTERNAL, NOT COMPUTE.INTERNAL
- name: Configure SSH proxy host.
  blockinfile:
    dest: "{{ ansible_env.HOME }}/.ssh/config"
    marker: "# {{ marker_vars|default(vpc.resource_tags.Organization) }}"
    block: |
      Host ip-{{ vpc.cidr_block.split('.')[0]}}-{{ vpc.cidr_block.split('.')[1]}}-*-*.{{ route53.domain }}
           ProxyCommand ssh -i ~/.ssh/{{ vpc.keypair }} -W %h:%p -q {{ vpc.image_user }}@{{ bastion_vars }}
           ServerAliveInterval 30
