---
# tasks file for aws.vpc
- name: Create VPC.
  ec2_vpc:
    aws_secret_key: "{{ vault.aws_secret_key }}"
    aws_access_key: "{{ vault.aws_access_key }}"
    region: "{{ vpc.region }}"
    state: "{{ vpc.state }}"
    cidr_block: "{{ vpc.cidr_block }}"
    internet_gateway: "{{ vpc.gateway }}"
    resource_tags: "{{ vpc.resource_tags }}"
    subnets: "{{ vpc.subnets }}"
  register: vpc_register
