---
# openvpn_terraform.yml
# ansible-playbook openvpn_terraform.yml -e "env=stuffs-demo keypair=dev"
# Initial AWS configuration, variables, and scrapes AWS public keys.
- hosts: localhost
  connection: local
  gather_facts: yes
  roles:
    # - role: localhost.ssh_key_configure
    - role: aws.ec2_facts
      filters:
        "tag:Environment": "{{ env }}"
        instance-state-name: running
    - role: localhost.aws_ssh_keys
    - role: ansible.groups_init

# Intial configuration of the OpenVPN server.  Will be skipped if not created/used.
# Initial raw configuration
- hosts: "{{ env }}-openvpn_public"
  become: yes
  gather_facts: no
  user: ubuntu
  roles:
    - role: ubuntu.raw_install_python

# Configure openvpn instance (skipped if not created)
- hosts: "{{ env }}-openvpn_public"
  become: yes
  gather_facts: yes
  remote_user: ubuntu
  vars_files:
    - vars/openvpn.yml
  roles:
    - role: instance.ssh_aws_public_key
    - role: instance.hosts
    - role: instance.docker_install
    - role: instance.openvpn_configure
    - role: instance.openvpn_create_user_config
