---
# wordpress.yml
#
# This playbook deploys an AWS infrastructure and two instances; a wordpress
#   instance and a mysql instance.  It deploys all infrastucture from the ground up.
#   All that is needed is an AWS account, an IAM access/secret key setup, and an
#   uploaded SSH key (defaults to defaultkey).
#
# Both instances use public IP addresses, so no bastion host is needed.
#
#####
# Initial AWS deployment
#####
- hosts: localhost
  connection: local
  gather_facts: yes

  vars_files:
    - vars/b_aws/aws.yml
    - vars/b_aws/vault.yml
    - vars/b_aws/wordpress.yml

  roles:
    - role: aws.vpc
    - role: aws.vpc_facts
      filters:
        "tag:Organization": b_aws
    - role: aws.routes
    - role: aws.securitygroups
    - role: aws.iam
    - role: aws.ec2
    - role: aws.ec2_facts
      filters:
        "tag:Organization": b_aws
    # - role: localhost.aws_ssh_keys
    # - role: ansible.groups_init
#
#
# #####
# # Initial raw configuration for bastionhost
# #####
# - hosts: bastionhost_public
#   become: yes
#   gather_facts: no
#   user: ubuntu
#
#   roles:
#     - role: ubuntu.raw_install_python
#
# #####
# # Configure NAT instance
# #####
# - hosts: bastionhost_public
#   become: yes
#   remote_user: ubuntu
#   gather_facts: yes
#
#   vars_files:
#     - vars/aws_infrastructure.yml
#
#   roles:
#     - role: instance.ssh_aws_public_key
#     - role: bastionhost.nat_config
#
# #####
# # Initial raw configuration for ALL instances
# #####
# - hosts: internal_system_private
#   become: yes
#   remote_user: ubuntu
#   gather_facts: no
#
#   roles:
#     - role: ubuntu.raw_install_python
#
# #####
# # Configure NAT instance
# #####
# - hosts: internal_system_private
#   become: yes
#   remote_user: ubuntu
#   gather_facts: yes
#
#   vars_files:
#     - vars/aws_infrastructure.yml
#
#   roles:
#     - role: instance.ssh_aws_public_key
#     - role: instance.apache_install
